# Generated by Django 5.2.15 on 2026-07-05 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('seat_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.venue')),
            ],
            options={
                'db_table': 'seats',
                'ordering': ['row', 'seat_number'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'row', 'seat_number'), name='unique_seat_per_venue')],
            },
        ),
    ]
